spring:
  application:
    name: app-user
debug: true

server:
  port: 9091
  servlet:
    context-path: /
    session:
      timeout: 300
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
